project:
  type: website
  output-dir: docs

website:
  title: "100DaysOfCode R"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mgrundt
      - icon: twitter
        href: https://twitter.com/MG_151823
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

